### ISSUE TITLE
Add Toggle GPIO

### ISSUE THREAD

**Issue by Rickln** [rern/RuneUI_GPIO#9]
Hi, is it possible to remove the timer and add for example buttons to toggle gpio in order to turn equipment on or of?

**Comment by rern** [comment]
Hi,
Disable: Menu > GPIO > Enable = Off
Disable timer: Menu > GPIO > Idle = none
Toggle on/off: Loudspeaker button/icon on the left of top bar

Please post your question in RuneAudio forum.
